name: Build
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.x'

      - name: Using Go version
        run: go version

      - name: Install deps
        run: go mod tidy

      - name: Build
        run: go build -o ./_out/wh-simulator ./cmd/wh-simulator.go

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: djvukovic/wh-simulator:latest
          labels: